### PR TITLE
Initial work on a Gapvis API

### PR DESCRIPTION
**Pull request by enridaga**
Created gapvis resources under packages controllers and models
Configured new router for books, generated json following the gapvis spec.

Regular small merges are better. Agreed?
Is code organization OK with the recogito2 codebase practice?

### CODE REVIEW

**Comment by rsimon** [comment]
Hi, 

that looks ok as a general principle. But I think we should restructure just a bit: 

- I wouldn't want a GapVis specific datamodel, living in parallel to the internal data model. Especially if you are fetching standard document metadata, which we can expose through a non-GapVis-specific API just as well. 
- Likewise, in terms of URL paths, I think a standard metadata JSON export could live either somewhere under `/api`, where all the other JSON API endpoints are located, or perhaps under `/downloads`, where all the batch exports are. (I assume you want to pull a specific, single book, so `/api` will probably be the most suitable place.)
- Integrating properly into the API, and with Recogito's standard data model, would also help to integrate it with the rest of the authorization framework. As it stands, the new controller methods bypass authorization and open up all metadata - open or closed - to anyone.

I may have some time to look into a more general mechanism, based on your code, on Thursday.

**Comment by enridaga** [comment]
(Datamodel) No it is not needed in principle, the important thing is that at the end the JSON satisfies the requirements of GapVis [1]. For the book list this might not be necessary as we can use DocumentRecord as model, to what extent this will be possible for the rest I can't say.

(URL patterns) Again, as soon as the layout satisfies [1] I do not really care. Reasons to keep a gapvis specific API are:
(1) we can be confident it will remain compatible with GapVis (no degrading over time because of changes not targeted to GapVis)
(2) not all the objects in recogito needs to be make available for GapVis
(3) the GapVis layout is a bit awkward, and also includes some very specific things, like the way texts and place citations are encoded. I do not see as making sense outside GapVis, honestly

Maybe, we can still keep a /gapvis API and the use the relevant code to also expose general purpose URLs... 
I agree on not duplicating code, but I like the story "Recogito implements the GapVis API" as well.





[1] https://github.com/enridaga/gapvis#api-specification

**Comment by enridaga** [comment]
(authorization) For what concern the GapVis API, it should be 100% open. Then of course we need to be sure that private data is not shared (happy to receive indications about how to do that).

**Comment by rsimon** [comment]
I'm open to have Recogito support the "GapVis data model". But we definitely need to avoid redundancies in the data model. Also, the fact that the current pull request bypasses all authorization mechanisms (and adds a bypass query that retrieves all document records from the DB, without any size limit) means I can't put this into production.

* I'll take a look about re-using DocumentRecord directly for the API. URL-wise this needs to live somewhere under the `/api/` base path. (It might take a bit of time until I get around to doing this though, unfortunately.) There, we can also re-use the standard auth mechanism easily.

* I assume you'll need access to the text content as well? Once we have a good way to expose the document metadata, it would be good to have your help again with regard to how the content should go over the wire.

**Pull request closed without merging**
